### ISSUE TITLE
CSD breaks

### ISSUE THREAD

**Issue by codic12** [torvic9/plasmafox#16] opened 2020-05-03 23:54 UTC
If you disable the title bar through the customize menu, which on standard firefox uses the GTK CSD, the window decorations fully disappear but no csd appears on plasmafox

**Comment by torvic9** [comment] 2020-05-04 06:24
Please share a screenshot.
I'm aware of an issue where the window control buttons disappear when using global menu.
If that's what you mean, then I'm afraid I have no clue how to fix it, maybe an issue with Ubuntu menubar patch.
Please also try with a new blank profile.

**Comment by codic12** [comment] 2020-05-04 15:15
Sure.
Normal Firefox:
![image](https://user-images.githubusercontent.com/48339289/80981781-44d11d00-8ddf-11ea-8917-2d8aa67ad01d.png)
Plasmafox:
![image](https://user-images.githubusercontent.com/48339289/80981836-574b5680-8ddf-11ea-9ec2-7e8149f2caf4.png)

New profile has no change :(

**Comment by torvic9** [comment] 2020-05-04 16:32
Thanks. It's the same issue I have here. I will investigate and hopefully find a solution.

**Comment by codic12** [comment] 2020-05-04 16:36
Thanks!

**Comment by codic12** [comment] 2020-05-04 16:38
> If that's what you mean, then I'm afraid I have no clue how to fix it, maybe an issue with Ubuntu menubar patch.

Maybe this is due to unity's hud and window buttons in titlebar?

**Comment by torvic9** [comment] 2020-05-04 16:40
Do you remember when the title bar was still OK?
It might also be one of the recent updates that broke something, perhaps `gtk3`.

**Comment by codic12** [comment] 2020-05-04 17:28
No, I just started using plasmafox, and it just didn't work out of the box :P

**Comment by torvic9** [comment] 2020-05-04 17:37
There is an updated version of Ubuntu's menubar patch available now.
I'll rebuild and report back.

EDIT: Funnily enough, Firefox 76 has been released... :)

**Comment by codic12** [comment] 2020-05-04 18:08
> There is an updated version of Ubuntu's menubar patch available now.
I'll rebuild and report back.

Thank you!

> EDIT: Funnily enough, Firefox 76 has been released... :)

I thought it was still in beta :)

**Comment by torvic9** [comment] 2020-05-04 19:16
FF 76 is ready and will be up shortly - but the bug is still there, although it seems it's slightly better...

**Comment by codic12** [comment] 2020-05-04 19:20
Ah, what do you mean by the bug is better?

**Comment by codic12** [comment] 2020-05-04 19:21
Oops, that was a mistake.
also I notice the (outdated) opensuse firefox in aur doesn't have this issue but global menus work

**Comment by torvic9** [comment] 2020-05-04 19:37
Well I think this bug appeared only quite recently, at least nobody reported anything.
I only noticed it when suddenly the minimize/maximize/close buttons were gone...

**Comment by codic12** [comment] 2020-05-04 20:25
:(
any ideas?

**Comment by torvic9** [comment] 2020-05-05 09:21
I tried a few things but up to now I don't have solution.
What I will do next is to install old 19.0.2 KDE ISO in a VBox and see whether the bug also occurs on that old version.

If anyone else has an idea, please don't hesitate.

**Comment by codic12** [comment] 2020-05-05 15:43
Hmm, maybe try removing patches and applying one patch at a time to see which one is causing the issue?

**Comment by torvic9** [comment] 2020-05-05 18:57
I tried a few things over many hours, including removing and changing patches, but due to the long compilation time (about 35 minutes) and a full time job, I cannot just endlessly rebuild and test.

Still, I have just finished uploading 76.0.
Issue is still there, but at least you're up-to-date, and you can still enable the title bar while we're waiting for a fix or more precisely to actually know what is wrong there - so many variables.. and it could also be a change in Plasma, in a system lib or in a theming engine that caused this, although I have some doubts.

**Comment by codic12** [comment] 2020-05-05 19:04
Alright, I understand. Thank you!

**Comment by torvic9** [comment] 2020-05-05 19:10
EDIT: of course enabling the title bar doesn't help. I cannot even maximize or change size of the window.
But one more thing: check full-screen mode with F11, I think this is how it should look.

**Comment by codic12** [comment] 2020-05-05 19:17
it works in fullscreen yeah

**Comment by torvic9** [comment] 2020-05-05 19:28
Maybe you can test something for me: (re)move `/usr/lib/plasmafox/browser/defaults/preferences/vendor.js` and start with a new clean profile. Maybe it's just some setting? 
I'll try a few more things now, but I won't look at it in the next few days, need a break :-)

**Comment by codic12** [comment] 2020-05-05 20:07
nope that did not work :(
"I'll try a few more things now, but I won't look at it in the next few days, need a break :-)"
Sure!! :)

**Comment by torvic9** [comment] 2020-06-04 19:04
Is there any improvement with 77.0.1?
I haven't looked at it and to be honest, I don't really know what can be done about it...

**Comment by codic12** [comment] 2020-06-04 20:33
I've moved away from manjaro to solus so cannot test, sorry

**Comment by hchr** [comment] 2020-07-18 06:47
78.0.2 Manjaro KDE
The issue is still there, if the title bar is disabled.
The window can be resized by dragging the sides with the mouse
If the sidebar is enabled, everything is ok
![image](https://user-images.githubusercontent.com/6417330/87846838-788df000-c8c2-11ea-9b96-2f53f57353f5.png)

**Comment by Alexander-Huang** [comment] 2020-08-06 08:49
The bug still exists on both latest firefox-kde-opensuse and plasmafox.Maybe it's not your fault but something with firefox itself.

**Comment by Aleksanaa** [comment] 2020-08-06 09:06
The bug still exists on both latest firefox-kde-opensuse and plasmafox.

Everytime I open these two the global menu doesn't appear soon,
then if I click on the desktop and click back to firefox,the global menu appears,and the CSD breaks.
 ![Screenshot_20200806_165529](https://user-images.githubusercontent.com/42209822/89512352-b321e300-d805-11ea-93fc-34f1bf04f9e2.png)

Just then I noticed something more interesting. I moved the mouse onto a notification(without clicking it),when the notification disappeared,the window decoration also disappeared and the global menu appeared.If I remove the global menu after the window decoration disappears,CSD comes back immediately.

Maybe it's not your fault but something with firefox itself.And I guess there's a relationship between the global menu and the disappearance of the window decorations.

**Comment by torvic9** [comment] 2020-08-12 14:36
Sorry for the late reply. 
Thanks for reporting, especially the fact that firefox-kde-opensuse is also affected...
It must be super annoying for global menu users, but unfortunately I cannot do much about it. 
I simply don't know what's wrong :-(

**Comment by torvic9** [comment] 2021-04-20 13:17
This should be fixed by now with Plasmafox 88.
Closed (please reopen if not fixed).

**Closed as completed by torvic9** 2021-04-20 13:17 UTC
Labels: bug
